"""add price_earnings and earnings_per_share to position

Revision ID: 3be158bb8731
Revises: 0ddf8900dfec
Create Date: 2026-06-25 11:37:33.486575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3be158bb8731'
down_revision: Union[str, Sequence[str], None] = '0ddf8900dfec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('position', sa.Column('price_earnings', sa.Float(), nullable=True))
    op.add_column('position', sa.Column('earnings_per_share', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('position', 'earnings_per_share')
    op.drop_column('position', 'price_earnings')
    # ### end Alembic commands ###
