"""create card, merchantrule and transaction tables

Revision ID: 4d6fde8d3582
Revises: c2c96137ef72
Create Date: 2026-06-24 20:13:13.635404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4d6fde8d3582'
down_revision: Union[str, Sequence[str], None] = 'c2c96137ef72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('closing_day', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_name'), 'card', ['name'], unique=True)
    op.create_table('merchantrule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pattern', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchantrule_pattern'), 'merchantrule', ['pattern'], unique=False)
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.Enum('MANUAL', 'VISION_PREVIEW', name='transactionsource'), nullable=False),
    sa.Column('status', sa.Enum('CONFIRMED', 'PENDING_REVIEW', name='transactionstatus'), nullable=False),
    sa.Column('installment_current', sa.Integer(), nullable=True),
    sa.Column('installment_total', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['transaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_card_id'), 'transaction', ['card_id'], unique=False)
    op.create_index(op.f('ix_transaction_parent_id'), 'transaction', ['parent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_parent_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_card_id'), table_name='transaction')
    op.drop_table('transaction')
    op.drop_index(op.f('ix_merchantrule_pattern'), table_name='merchantrule')
    op.drop_table('merchantrule')
    op.drop_index(op.f('ix_card_name'), table_name='card')
    op.drop_table('card')
    # ### end Alembic commands ###
