"""create income fixed_expense variable_expense tables

Revision ID: 72bd333aaac6
Revises: 3be158bb8731
Create Date: 2026-06-25 22:20:04.327334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '72bd333aaac6'
down_revision: Union[str, Sequence[str], None] = '3be158bb8731'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('income',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_income_month'), 'income', ['month'], unique=False)
    op.create_index(op.f('ix_income_year'), 'income', ['year'], unique=False)
    op.create_table('fixedexpense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fixedexpense_month'), 'fixedexpense', ['month'], unique=False)
    op.create_index(op.f('ix_fixedexpense_year'), 'fixedexpense', ['year'], unique=False)
    op.create_table('variableexpense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_variableexpense_month'), 'variableexpense', ['month'], unique=False)
    op.create_index(op.f('ix_variableexpense_year'), 'variableexpense', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_variableexpense_year'), table_name='variableexpense')
    op.drop_index(op.f('ix_variableexpense_month'), table_name='variableexpense')
    op.drop_table('variableexpense')
    op.drop_index(op.f('ix_fixedexpense_year'), table_name='fixedexpense')
    op.drop_index(op.f('ix_fixedexpense_month'), table_name='fixedexpense')
    op.drop_table('fixedexpense')
    op.drop_index(op.f('ix_income_year'), table_name='income')
    op.drop_index(op.f('ix_income_month'), table_name='income')
    op.drop_table('income')
    # ### end Alembic commands ###
