"""add allocation_target table

Revision ID: 7fe01dca9671
Revises: 1b2efd06ac8f
Create Date: 2026-06-25 06:49:16.852135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7fe01dca9671'
down_revision: Union[str, Sequence[str], None] = '1b2efd06ac8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allocationtarget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_type', sa.Enum('STOCK', 'FII', 'ETF', 'FIXED_INCOME', 'CRYPTO', name='assettype'), nullable=False),
    sa.Column('target_percentage', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allocationtarget_asset_type'), 'allocationtarget', ['asset_type'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_allocationtarget_asset_type'), table_name='allocationtarget')
    op.drop_table('allocationtarget')
    # ### end Alembic commands ###
