"""add due_day and seed billing cycle days

Revision ID: a62cc0368dd7
Revises: af4c484405d1
Create Date: 2026-06-27 10:14:14.672590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a62cc0368dd7'
down_revision: Union[str, Sequence[str], None] = 'af4c484405d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_BILLING_DAYS = {
    "PicPay": {"closing_day": 7, "due_day": 15},
    "Inter": {"closing_day": 8, "due_day": 18},
    "Santander": {"closing_day": 3, "due_day": 13},
}


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('due_day', sa.Integer(), nullable=True))
    # ### end Alembic commands ###

    card_table = sa.table(
        "card",
        sa.column("name", sa.String),
        sa.column("closing_day", sa.Integer),
        sa.column("due_day", sa.Integer),
    )
    for name, days in _BILLING_DAYS.items():
        op.execute(
            card_table.update()
            .where(card_table.c.name == name)
            .values(closing_day=days["closing_day"], due_day=days["due_day"])
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'due_day')
    # ### end Alembic commands ###
