"""add target_yield_pct to position

Revision ID: abc3e65975f9
Revises: 72bd333aaac6
Create Date: 2026-06-26 23:39:19.135101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'abc3e65975f9'
down_revision: Union[str, Sequence[str], None] = '72bd333aaac6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('position', sa.Column('target_yield_pct', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('position', 'target_yield_pct')
    # ### end Alembic commands ###
