"""add stock_split table

Revision ID: af4c484405d1
Revises: abc3e65975f9
Create Date: 2026-06-27 00:01:56.344630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'af4c484405d1'
down_revision: Union[str, Sequence[str], None] = 'abc3e65975f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocksplit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('ratio_from', sa.Float(), nullable=False),
    sa.Column('ratio_to', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['position.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stocksplit_position_id'), 'stocksplit', ['position_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stocksplit_position_id'), table_name='stocksplit')
    op.drop_table('stocksplit')
    # ### end Alembic commands ###
