"""create position contribution dividend snapshot reserve tables

Revision ID: dc1cdf23f373
Revises: d5be9e9e731e
Create Date: 2026-06-24 23:37:17.214500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dc1cdf23f373'
down_revision: Union[str, Sequence[str], None] = 'd5be9e9e731e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emergencyreserve',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('balance_cents', sa.Integer(), nullable=False),
    sa.Column('cdi_percentage', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('asset_type', sa.Enum('STOCK', 'FII', 'ETF', 'FIXED_INCOME', 'CRYPTO', name='assettype'), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_price_cents', sa.Integer(), nullable=True),
    sa.Column('last_price_fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_position_ticker'), 'position', ['ticker'], unique=True)
    op.create_table('pricesnapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('portfolio_value_cents', sa.Integer(), nullable=False),
    sa.Column('emergency_reserve_value_cents', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricesnapshot_month'), 'pricesnapshot', ['month'], unique=True)
    op.create_table('contribution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_price_cents', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['position.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contribution_position_id'), 'contribution', ['position_id'], unique=False)
    op.create_table('dividend',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['position.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dividend_position_id'), 'dividend', ['position_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dividend_position_id'), table_name='dividend')
    op.drop_table('dividend')
    op.drop_index(op.f('ix_contribution_position_id'), table_name='contribution')
    op.drop_table('contribution')
    op.drop_index(op.f('ix_pricesnapshot_month'), table_name='pricesnapshot')
    op.drop_table('pricesnapshot')
    op.drop_index(op.f('ix_position_ticker'), table_name='position')
    op.drop_table('position')
    op.drop_table('emergencyreserve')
    # ### end Alembic commands ###
