"""add is_paid to expenses and card invoice payment table

Revision ID: ecc06d759109
Revises: fcc537a6f02d
Create Date: 2026-07-08 11:45:56.231016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ecc06d759109'
down_revision: Union[str, Sequence[str], None] = 'fcc537a6f02d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cardinvoicepayment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_id', 'year', 'month')
    )
    op.create_index(op.f('ix_cardinvoicepayment_card_id'), 'cardinvoicepayment', ['card_id'], unique=False)
    op.create_index(op.f('ix_cardinvoicepayment_month'), 'cardinvoicepayment', ['month'], unique=False)
    op.create_index(op.f('ix_cardinvoicepayment_year'), 'cardinvoicepayment', ['year'], unique=False)
    op.add_column(
        'fixedexpense',
        sa.Column('is_paid', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        'variableexpense',
        sa.Column('is_paid', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('variableexpense', 'is_paid')
    op.drop_column('fixedexpense', 'is_paid')
    op.drop_index(op.f('ix_cardinvoicepayment_year'), table_name='cardinvoicepayment')
    op.drop_index(op.f('ix_cardinvoicepayment_month'), table_name='cardinvoicepayment')
    op.drop_index(op.f('ix_cardinvoicepayment_card_id'), table_name='cardinvoicepayment')
    op.drop_table('cardinvoicepayment')
    # ### end Alembic commands ###
