"""add roe_percentage to position

Revision ID: f08d29c3fa84
Revises: 69b35846310d
Create Date: 2026-06-25 11:00:59.726506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f08d29c3fa84'
down_revision: Union[str, Sequence[str], None] = '69b35846310d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('position', sa.Column('roe_percentage', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('position', 'roe_percentage')
    # ### end Alembic commands ###
