export type ThemeName = 'warm' | 'matrix' | 'hotline-miami'

export const THEME_LABELS: Record<ThemeName, string> = {
  warm: 'Quente (padrão)',
  matrix: 'Matrix',
  'hotline-miami': 'Hotline Miami',
}

export const THEME_VARIABLES = [
  'background',
  'foreground',
  'card',
  'card-foreground',
  'popover',
  'popover-foreground',
  'primary',
  'primary-foreground',
  'secondary',
  'secondary-foreground',
  'muted',
  'muted-foreground',
  'accent',
  'accent-foreground',
  'destructive',
  'success',
  'success-foreground',
  'warning',
  'warning-foreground',
  'border',
  'input',
  'ring',
] as const

export type ThemeVariable = (typeof THEME_VARIABLES)[number]

export const themes: Record<ThemeName, Record<ThemeVariable, string>> = {
  warm: {
    background: '#14110f',
    foreground: '#f1ece6',
    card: '#1d1815',
    'card-foreground': '#f1ece6',
    popover: '#1d1815',
    'popover-foreground': '#f1ece6',
    primary: '#f0a868',
    'primary-foreground': '#1c1306',
    secondary: '#261f1a',
    'secondary-foreground': '#f1ece6',
    muted: '#261f1a',
    'muted-foreground': '#b3a89d',
    accent: '#2c2118',
    'accent-foreground': '#f1ece6',
    destructive: '#f0654f',
    success: '#4fd6a5',
    'success-foreground': '#052e1f',
    warning: '#fbbf24',
    'warning-foreground': '#1c1306',
    border: '#34291f',
    input: '#34291f',
    ring: '#f0a868',
  },
  matrix: {
    background: '#000000',
    foreground: '#33ff33',
    card: '#0a0e0a',
    'card-foreground': '#33ff33',
    popover: '#0a0e0a',
    'popover-foreground': '#33ff33',
    primary: '#00ff41',
    'primary-foreground': '#000000',
    secondary: '#0d1f0d',
    'secondary-foreground': '#33ff33',
    muted: '#0d1f0d',
    'muted-foreground': '#5fae5f',
    accent: '#143314',
    'accent-foreground': '#33ff33',
    destructive: '#ff3333',
    success: '#00ff41',
    'success-foreground': '#000000',
    warning: '#ffcc00',
    'warning-foreground': '#000000',
    border: '#1a3d1a',
    input: '#1a3d1a',
    ring: '#00ff41',
  },
  'hotline-miami': {
    background: '#1a0b2e',
    foreground: '#f7f0ff',
    card: '#2d1b4e',
    'card-foreground': '#f7f0ff',
    popover: '#2d1b4e',
    'popover-foreground': '#f7f0ff',
    primary: '#ff2eb0',
    'primary-foreground': '#1a0b2e',
    secondary: '#3a2462',
    'secondary-foreground': '#f7f0ff',
    muted: '#3a2462',
    'muted-foreground': '#c2a9e6',
    accent: '#00e5ff',
    'accent-foreground': '#1a0b2e',
    destructive: '#ff4757',
    success: '#00ffa3',
    'success-foreground': '#1a0b2e',
    warning: '#ffd23f',
    'warning-foreground': '#1a0b2e',
    border: '#5a3d8a',
    input: '#5a3d8a',
    ring: '#ff2eb0',
  },
}
